# Generated by Django 2.2.28 on 2025-03-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidfood', '0002_auto_20250326_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
