# Generated by Django 2.2.3 on 2025-03-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidfood', '0002_place_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='placecategory',
            name='plural_name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
