# Generated by Django 2.2.3 on 2025-03-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidfood', '0003_auto_20250327_0149'),
        ('unidfood', '0003_placecategory_plural_name'),
    ]

    operations = [
    ]
