# Generated by Django 2.2.3 on 2025-03-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidfood', '0004_merge_20250327_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
