# Generated by Django 2.2.3 on 2025-03-28 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unidfood', '0005_auto_20250328_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='attendees',
            field=models.ManyToManyField(related_name='meetups', to=settings.AUTH_USER_MODEL),
        ),
    ]
